version: '3'

networks:
  cvtruenetwork:

services:
  # PHP Service
  app:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/var/www/html
    ports:
      - "8080:8080"
    depends_on:
      - mysqldb
    networks:
      - cvtruenetwork

  # MySQL Service
  mysqldb:
    image: mysql:latest
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: mysql
      MYSQL_USER: code
      MYSQL_PASSWORD: 123456
    ports:
      - "3306:3306"
    volumes:
      - mysql-data:/var/lib/mysql
    networks:
      - cvtruenetwork

volumes:
  mysql-data:
