version: '3'

services:
  php:
    build:
      context: .
    volumes:
      - .:/var/www/html
    working_dir: /var/www/html
    depends_on:
      - mysql

  nginx:
    image: nginx:latest
    ports:
      - "8080:80"
    volumes:
      - .:/var/www/html
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - php

  mysql:
    image: mysql:latest
    environment:
      MYSQL_DATABASE: cv_true
      MYSQL_USER: code
      MYSQL_PASSWORD: 123456
      MYSQL_ROOT_PASSWORD: 123456
    ports:
      - "3306:3306"

